### ISSUE TITLE
Cannot Find Symbol build errors for clients

### ISSUE THREAD

**Issue by p-oshea** [emerge-ehri/FHIRGenomicsImplementation#1]
Hello, I am looking to use the client in a project of mine, but have run into a build problem. it looks like the last commit removed the Class file, but not the references and calls to them. Any advice on getting this to build? 

`[INFO] Scanning for projects...
[INFO]
[INFO] -----------------< edu.bcm.hgsc.fhir:hgsc-fhir-client >-----------------
[INFO] Building hgsc-fhir-client Webapp 0.0.1
[INFO] --------------------------------[ war ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ hgsc-fhir-client ---
[INFO] Deleting /Users/poshea/Documents/GitHub/FHIRGenomicsImplementation/hgsc-fhir-client/target
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ hgsc-fhir-client ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ hgsc-fhir-client ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 44 source files to /Users/poshea/Documents/GitHub/FHIRGenomicsImplementation/hgsc-fhir-client/target/classes
[INFO] /Users/poshea/Documents/GitHub/FHIRGenomicsImplementation/hgsc-fhir-client/src/main/java/edu/bcm/hgsc/fhir/services/FileUploadServiceImpl.java: /Users/poshea/Documents/GitHub/FHIRGenomicsImplementation/hgsc-fhir-client/src/main/java/edu/bcm/hgsc/fhir/services/FileUploadServiceImpl.java uses unchecked or unsafe operations.
[INFO] /Users/poshea/Documents/GitHub/FHIRGenomicsImplementation/hgsc-fhir-client/src/main/java/edu/bcm/hgsc/fhir/services/FileUploadServiceImpl.java: Recompile with -Xlint:unchecked for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/poshea/Documents/GitHub/FHIRGenomicsImplementation/hgsc-fhir-client/src/main/java/edu/bcm/hgsc/fhir/utils/FhirResourcesMappingUtils.java:[63,57] cannot find symbol
  symbol:   class DxCNVVariantsValueMapper
  location: class edu.bcm.hgsc.fhir.utils.FhirResourcesMappingUtils
[ERROR] /Users/poshea/Documents/GitHub/FHIRGenomicsImplementation/hgsc-fhir-client/src/main/java/edu/bcm/hgsc/fhir/services/FileUploadServiceImpl.java:[669,93] cannot find symbol
  symbol:   variable orgName
  location: class edu.bcm.hgsc.fhir.services.FileUploadServiceImpl
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.898 s
[INFO] Finished at: 2020-11-09T13:07:11-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project hgsc-fhir-client: Compilation failure: Compilation failure:
[ERROR] /Users/poshea/Documents/GitHub/FHIRGenomicsImplementation/hgsc-fhir-client/src/main/java/edu/bcm/hgsc/fhir/utils/FhirResourcesMappingUtils.java:[63,57] cannot find symbol
[ERROR]   symbol:   class DxCNVVariantsValueMapper
[ERROR]   location: class edu.bcm.hgsc.fhir.utils.FhirResourcesMappingUtils
[ERROR] /Users/poshea/Documents/GitHub/FHIRGenomicsImplementation/hgsc-fhir-client/src/main/java/edu/bcm/hgsc/fhir/services/FileUploadServiceImpl.java:[669,93] cannot find symbol
[ERROR]   symbol:   variable orgName
[ERROR]   location: class edu.bcm.hgsc.fhir.services.FileUploadServiceImpl
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException`

**Comment by Mullai** [comment]
Added Fei, the primary developer to this thread.

HI Fei,
Can you please help with this request?
Thanks,
Mullai


________________________________

**Comment by feiyanbcm** [comment]
@p-oshea can you please try now?

**Comment by p-oshea** [comment]
hi @feiyanbcm I have successfully built it now, thanks!
